name: Track Master

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # main
      with:
        persist-credentials: false
