name: Track Master

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # main
      with:
        persist-credentials: false
