name: Track Master

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main
      with:
        persist-credentials: false
